### ISSUE TITLE
Bed/Setspawn respawn crash

### ISSUE THREAD

**Issue by SirFell** [vorquel/SimpleSkyGrid#5]
There is issue with player respawn after bed/setspawn is used:

```
java.lang.NullPointerException: Ticking memory connection
    at vorquel.mod.simpleskygrid.event.SpawnFixer.playerRespawn(SpawnFixer.java:41)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_1291_SpawnFixer_playerRespawn_PlayerRespawnEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.firePlayerRespawnEvent(FMLCommonHandler.java:560)
    at net.minecraft.server.management.ServerConfigurationManager.func_72368_a(ServerConfigurationManager.java:486)
    at net.minecraft.network.NetHandlerPlayServer.func_147342_a(NetHandlerPlayServer.java:860)
    at net.minecraft.network.play.client.C16PacketClientStatus.func_148833_a(SourceFile:50)
    at net.minecraft.network.play.client.C16PacketClientStatus.func_148833_a(SourceFile:8)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Crash is hapening in 1-3 seconds after respawn.

Maybe something in modpack is causing this; Here is [mod list](http://pastebin.com/Gn1dgbgJ)
And full [crashlog](http://pastebin.com/k89idjhX)

**Comment by Vorquel** [comment]
Thank you for submitting this bug. I will try to find and fix it asap.

**Comment by SirFell** [comment]
I'll try to help as much as i can. Well, not a great java programmer, but still =D

**Comment by Vorquel** [comment]
I have confirmed that this crash happens without any other mods present. That's all on me.

**Comment by Vorquel** [comment]
I'm pretty sure I fixed the issue, but if you would be so kind as to double check for me, I would appreciate it. Here's a link to a build with the fix: https://dl.dropboxusercontent.com/u/13739385/SimpleSkyGrid-1.7.10-dev.jar

**Comment by SirFell** [comment]
I will test now.

_Edit: Just tested it, all works fine. Thanks for fast support._

**Comment by SirFell** [comment]
So, when to wait for proper release on curse?

**Comment by Vorquel** [comment]
About 10 minutes.

**Comment by SirFell** [comment]
Ok, thanks.

**Comment by Vorquel** [comment]
Glad I could help.
